### ISSUE TITLE
A Call can only be used once.

### ISSUE THREAD

**Issue by wellington-barbosa-daitan** [drakeet/retrofit-agera-call-adapter#4]
Retrofit´s documentation (http://square.github.io/retrofit/2.x/retrofit/retrofit2/Call.html) tells you how to use one multiple times:

> Use clone() to make multiple calls with the same parameters to the same webserver; this may be used to implement polling or to retry a failed call.

Stacktrace:
**java.lang.IllegalStateException: Already executed.
                                                                           at retrofit2.OkHttpCall.execute(OkHttpCall.java:148)
                                                                           at me.drakeet.retrofit2.adapter.agera.CallResponseSupplier.get(CallResponseSupplier.java:45)
                                                                           at me.drakeet.retrofit2.adapter.agera.CallResponseSupplier.get(CallResponseSupplier.java:32)
                                                                           at com.google.android.agera.CompiledRepository.runGetFrom(CompiledRepository.java:338)
                                                                           at com.google.android.agera.CompiledRepository.runFlowFrom(CompiledRepository.java:299)
                                                                           at com.google.android.agera.CompiledRepository.run(CompiledRepository.java:541)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at java.lang.Thread.run(Thread.java:818)**

I found the problem in these classes: **CallSupplier** and **CallResponseSupplier**

I just changed: `Response<T> response = call.execute();` to `Response<T> response = call.clone().execute();`

**Comment by drakeet** [comment]
Thank you, you are right, I will fix it tonight! Or, you can add pull request before the evening. We are in the morning now.

**Comment by drakeet** [comment]
@wellington-barbosa-daitan 
Could you give me the triggering `IllegalStateException` code? I need to do some testing, I can not reproduce it. Thanks!

**Comment by wellington-barbosa-daitan** [comment]
@drakeet  I´m making a test request to this API:
https://api.github.com/search/repositories?q=language:Java&sort=stars&page=1

I create the request onCreate. When my app enters onStop and comes back again the app crashes.
